#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nano'
export VISUAL='nano'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU path fpath manpath cdpath

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
#	/Users/jking/.rbenv/shims
path=(
	/usr/local/opt/sqlite/bin
	/usr/local/opt/sqlite-analyzer/bin
	/usr/local/opt/ruby/bin
	/usr/local/opt/qt/bin
	/usr/local/opt/curl/bin
	/usr/local/opt/gettext/bin
	/usr/local/opt/icu4c/bin
	/usr/local/opt/icu4c/sbin
	/usr/local/opt/binutils/bin
	/usr/local/opt/coreutils/libexec/gnubin
	/usr/local/opt/findutils/libexec/gnubin
	/usr/local/opt/inetutils/libexec/gnubin
	/usr/local/opt/texinfo/bin
	/usr/local/opt/ed/libexec/gnubin
	/usr/local/opt/calc/libexec/cscript
	/usr/local/opt/opencv3/bin
	/usr/local/opt/unzip/bin
	/usr/local/{,s}bin
	/usr/{,s}bin
	/{,s}bin
	$GOROOT
	/Applications/VICE/tools
	/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin
	/usr/local/lib/ruby/gems/2.7.0/bin
  $path
)
for path_file in /etc/paths.d/*(.N); do
	path+=($(<$path_file))
done

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
